services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Match the exposed port in the Dockerfile
    container_name: cinever_be
    env_file:
      - .env
    