spring.application.name=cineverse-be
spring.config.import=optional:file:.env[.properties]
# Firebase
firebase.config.path=src/main/resources/serviceAccountKey.json
com.example.firebase.web-api-key=${WEB-API-KEY}
com.example.firebase.private-key=serviceAccountKey.json