spring.application.name=cineverse-be
spring.config.import=optional:file:.env[.properties]

# Swagger
springdoc.swagger-ui.use-root-path=true

# Firebase
firebase.config.path=src/main/resources/serviceAccountKey.json
com.example.firebase.web-api-key=${WEB_API_KEY}
com.example.firebase.private-key=serviceAccountKey.json

# TMDB
tmdb.api.base-url=https://api.themoviedb.org/3/
tmdb.api.base-image-url=https://image.tmdb.org/t/p/
tmdb.credentials.access-token=${TMDB_ACCESS_TOKEN}