on:
  pull_request:
    branches:
      - deploy
  push:
    branches:
      - deploy

name: "Build & Release spring app image to docker hub"
jobs:
  build:
    name: Build & Release spring app image to docker hub
    runs-on: ubuntu-latest #windows-latest
    steps:
      # 1. checkout source code in repository
      - uses: actions/checkout@v3

      # create file .env
      - name: Create .env file
        run: |
          echo "WEB_API_KEY=${{ secrets.WEB_API_KEY }}" >> ./.env
          echo "TMDB_ACCESS_TOKEN=${{ secrets.TMDB_ACCESS_TOKEN }}" >> ./.env
          echo "FIREBASE_CREDENTIALS_JSON=${{ secrets.FIREBASE_CREDENTIALS_JSON }}" >> ./.env
          echo "HAS_SWAGGER=${{ secrets.HAS_SWAGGER }}" >> ./.env
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> ./.env
          echo "DB=${{ secrets.DB }}" >> ./.env
          echo "DATABASE_URI_CLOUD=${{ secrets.DATABASE_URI_CLOUD }}" >> ./.env
          echo "DATABASE_URI_CLOUD1=${{ secrets.DATABASE_URI_CLOUD1 }}" >> ./.env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> ./.env
          echo "AI_SERVICE_BASE_URL=${{ secrets.AI_SERVICE_BASE_URL }}" >> ./.env
          echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> ./.env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> ./.env
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> ./.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> ./.env
          echo "DOMAIN_AUTH_CALLBACK_URL=${{ secrets.DOMAIN_AUTH_CALLBACK_URL }}" >> ./.env
      
      # Load Google Service file
      # - name: Load Google Service file
      #   env:
      #     DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      #   run: |
      #     echo $env:DATA | Out-File -FilePath google-services-base64.txt
      #     $base64 = Get-Content google-services-base64.txt
      #     [System.Convert]::FromBase64String($base64) | Set-Content -Path ./android/app/google-services.json -AsByteStream
      #     Get-Content ./android/app/google-services.json

      #echo $DATA | base64 -di > ./android/app/google-services.json
      
      # # 2. install Java
      # - uses: actions/setup-java@v2
      #   with:
      #     java-version: '17.x'
      #     distribution: 'temurin'
      #     cache: maven
      
      # - name: Build with Maven
      #   run: mvn clean install
      
      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t webdevelopmentadvanced2425/cineverse_be:latest .

      # 4. Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u webdevelopmentadvanced2425 -p tientructhinh
          docker push webdevelopmentadvanced2425/cineverse_be:latest
          
      # echo webdevelopmentadvanced2425 | docker login -u tientructhinh --password-stdin
          #echo "tientructhinh" | docker login -u "webdevelopmentadvanced2425" --password-stdin
      # # 3. Build Docker image
      # - name: Build & push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: webdevelopmentadvanced2425/cineverse_be
      #     tags: latest
      #     registry: docker.io
      #     dockerfile: Dockerfile
      #     username: webdevelopmentadvanced2425
      #     password: tientructhinh

    #  env:
    #       FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

#Warning: Artifact pattern :build/app/outputs/apk/release/*.apk did not match any files